# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 507abe2345f2f65d271c997e5895970a5d63dd6435cb16ee0daa3dbb4cd5f08d18e8e8ea04aa6aaca122892cbe53e65aacd209c0221e8e848971be89bf078364

test:
  secret_key_base: 2c6b9479d5a3229e95a0072f0dc28119a841186acdbb60de79a0c297e887044f8e72f4b8c2775c740f6ef025d9b7dd3876fc3eba87b33e26ed27a63ee20ce7b6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
